#Rename to Config.toml

log_level = "DEBUG"

[[listeners]]
type = "jabber"
name = "example jabber"
jid = ""
password = ""
host = ""
port = 5222
room_list = ["A", "B", "C"]


[[listeners]]
type = "slack"
name = "example slack"
token = ""
