#Rename to Config.toml

log_level = "DEBUG"

[[listeners]]
type = "jabber"
name = "example jabber"
jid = ""
password = ""
host = ""
port = 5222
channel_list = ["A", "B", "C"]
pm_list = ["D"]


[[listeners]]
type = "slack"
name = "example slack"
token = ""
channel_list = ["A", "B", "C"]
pm_list = ["D"]

#Note: You only need one discord entry per login, each login will capter the specified servers
[[listeners]]
type = "discord"
name = "example discord"
email = ""
password = ""
#Note that discord uses channel/user ID, not names for these:
channel_list = ["11111111111111", "22222222222222222", "3333333333333333"]
pm_list = ["444444444444444444444"]
